version: '3'
services:
  postgres:
    volumes:
    - /home/vasa/data/:/data/pg
    environment:
      POSTGRES_PASSWORD: example
    ports:
    - 5432:5432
    networks:
    - my-pg-network

networks:
  my-pg-network: